#ifndef __GODOT_MODULE_ENET_REPLICATION_CONSTANTS_H
#define __GODOT_MODULE_ENET_REPLICATION_CONSTANTS_H

const int REPLICATION_MANAGER_PORT = 30503;
const int REPLICATION_MANAGER_SERVER_CONNECTIONS = 20;

enum REPLICATION_PACKET_TYPE
{
    NODE_UPDATE = 0
};

#endif
